"""initial schema

Revision ID: 5038af58d124
Revises: 
Create Date: 2026-05-11 15:14:16.378436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5038af58d124'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('uq_booking_seat_id'), if_exists=True)
        batch_op.create_index(batch_op.f('ix_booking_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_payment_status'), ['payment_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_seat_id'), ['seat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_booking_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('unique_booking_seat', ['seat_id'])
        batch_op.create_foreign_key(None, 'payment_transaction', ['payment_id'], ['id'])

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorite_film_id'), ['film_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorite_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_film_director'), ['director'], unique=False)
        batch_op.create_index(batch_op.f('ix_film_genre'), ['genre'], unique=False)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_film_id'), ['film_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_seat_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_seat_status'), ['status'], unique=False)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.alter_column('hall_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_index('idx_session_hall_start_time', ['hall_id', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_film_id'), ['film_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_hall_id'), ['hall_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_session_status'), ['status'], unique=False)
        batch_op.create_foreign_key(None, 'hall', ['hall_id'], ['id'])

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ticket_booking_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('idx_ticket_scanned_by_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('uq_ticket_token'), if_exists=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('user_email_key'), type_='unique', if_exists=True)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'), if_exists=True)
        batch_op.create_unique_constraint(batch_op.f('user_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_ticket_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('idx_ticket_scanned_by_id'), ['scanned_by_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_ticket_booking_id'), ['booking_id'], unique=False)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey', if_exists=True)
        batch_op.drop_index(batch_op.f('ix_session_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_session_hall_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_session_film_id'), if_exists=True)
        batch_op.drop_index('idx_session_hall_start_time', if_exists=True)
        batch_op.alter_column('hall_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_seat_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_seat_session_id'), if_exists=True)

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_user_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_review_film_id'), if_exists=True)

    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_film_genre'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_film_director'), if_exists=True)

    with op.batch_alter_table('favorite', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorite_user_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_favorite_film_id'), if_exists=True)

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey', if_exists=True)
        batch_op.drop_constraint('unique_booking_seat', type_='unique', if_exists=True)
        batch_op.drop_index(batch_op.f('ix_booking_user_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_booking_seat_id'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_booking_payment_status'), if_exists=True)
        batch_op.drop_index(batch_op.f('ix_booking_payment_id'), if_exists=True)
        batch_op.create_index(batch_op.f('uq_booking_seat_id'), ['seat_id'], unique=True)

    # ### end Alembic commands ###
